### ISSUE TITLE
Is it compatible with exordium?

### ISSUE THREAD

**Issue by ardissaps** [shizotoaster/SmoothMenuRefabricated#1]

**Comment by shizotoaster** [comment]
Idk, try it and see

**Comment by Felix14-v2** [comment]
> _No description provided._

Exordium forcefully limits FPS of GUI's with a max value of 60, just like on the vanilla title screen. You disable the title screen FPS limit with SmoothMenu and then limit it with Exordium, so i don't think this makes sense.
