### ISSUE TITLE
1.21 PLZZZZZZZZ!!!!!!

### ISSUE THREAD

**Issue by iCuraCN** [shizotoaster/SmoothMenuRefabricated#3]
1.21 PLZZZZZZZZ!!!!!!

**Comment by shizotoaster** [comment]
It is compatible with 1.21 but I forgot to mark it as compatible on modrinth and curseforge

**Comment by Felix14-v2** [comment]
You can also use [Dynamic FPS](https://modrinth.com/mod/dynamic-fps) — it already has this feature (disabled by default though)

**Comment by iCuraCN** [comment]
> It is compatible with 1.21 but I forgot to mark it as compatible on modrinth and curseforge

OK THANK!
